### ISSUE TITLE
Add Japanese Regional Icons for V4.

### ISSUE THREAD

**Issue by niksavc** [mrdarrengriffin/google-weather-icons#3]
![image](https://github.com/mrdarrengriffin/google-weather-icons/assets/58150480/e16e2598-9f77-4fb5-ae6b-3afb8149bc69)
https://www.gstatic.com/weather/conditions2023/2023.1/svg/cloudy_with_rain_dark.svg
https://www.gstatic.com/weather/conditions2023/2023.1/svg/cloudy_with_snow_dark.svg
https://www.gstatic.com/weather/conditions2023/2023.1/svg/cloudy_with_sunny_dark.svg
https://www.gstatic.com/weather/conditions2023/2023.1/svg/sunny_with_snow_dark.svg
https://www.gstatic.com/weather/conditions2023/2023.1/svg/sunny_with_rain_dark.svg
https://www.gstatic.com/weather/conditions2023/2023.1/svg/sunny_with_cloudy_dark.svg
https://www.gstatic.com/weather/conditions2023/2023.1/svg/rain_with_snow_dark.svg
https://www.gstatic.com/weather/conditions2023/2023.1/svg/rain_with_sunny_dark.svg
https://www.gstatic.com/weather/conditions2023/2023.1/svg/rain_with_cloudy_dark.svg
https://www.gstatic.com/weather/conditions2023/2023.1/svg/snow_with_rain_dark.svg
https://www.gstatic.com/weather/conditions2023/2023.1/svg/snow_with_sunny_dark.svg
https://www.gstatic.com/weather/conditions2023/2023.1/svg/snow_with_cloudy_dark.svg
https://www.gstatic.com/weather/conditions2023/2023.1/svg/cloudy_with_rain_light.svg
https://www.gstatic.com/weather/conditions2023/2023.1/svg/cloudy_with_snow_light.svg
https://www.gstatic.com/weather/conditions2023/2023.1/svg/cloudy_with_sunny_light.svg
https://www.gstatic.com/weather/conditions2023/2023.1/svg/sunny_with_snow_light.svg
https://www.gstatic.com/weather/conditions2023/2023.1/svg/sunny_with_rain_light.svg
https://www.gstatic.com/weather/conditions2023/2023.1/svg/sunny_with_cloudy_light.svg
https://www.gstatic.com/weather/conditions2023/2023.1/svg/rain_with_snow_light.svg
https://www.gstatic.com/weather/conditions2023/2023.1/svg/rain_with_sunny_light.svg
https://www.gstatic.com/weather/conditions2023/2023.1/svg/rain_with_cloudy_light.svg
https://www.gstatic.com/weather/conditions2023/2023.1/svg/snow_with_rain_light.svg
https://www.gstatic.com/weather/conditions2023/2023.1/svg/snow_with_sunny_light.svg
https://www.gstatic.com/weather/conditions2023/2023.1/svg/snow_with_cloudy_light.svg

Missing: 
sunny_and_cloudy, sunny_and_rain, sunny_and_snow, cloudy_and_sunny, cloudy_and_rain, cloudy_and_snow, snow_and_cloudy, snow_and_rain, snow_and_sunny, rain_and_sunny, rain_and_snow, rain_and_cloudy.

**Comment by mrdarrengriffin** [comment]
I've pulled, optimised and added these icons into the repo. Thank you for your contribution!
